version: '3.8'

services:
  api_gateway:
    build:
      context: /backend/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - authservice
      - transactionsservice
      - shopservice
      - notificationsservice

  authservice:
    build:
      context: /backend/auth_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: auth_service.settings
      DJANGO_SUPERUSER_USERNAME: k1r1eiiika
      DJANGO_SUPERUSER_EMAIL: k1r1eiiika@example.com
      DJANGO_SUPERUSER_PASSWORD: 12345
    depends_on:
      - auth_db
    ports:
      - "8001:8000"

  auth_consumer:
    build:
      context: /backend/auth_service
      dockerfile: Dockerfile
    command: [ "python", "accounts/services/spend_money_consumer.py" ]
    environment:
      PYTHONPATH: /backend/auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: auth_service.settings
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - auth_db
      - rabbitmq
    volumes:
      - .:/app


  auth_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres_auth
    ports:
      - "5434:5432"

  transactionsservice:
    build:
      context: /backend/transactions_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: transactions_service.settings
      DJANGO_SUPERUSER_USERNAME: k1r1eiiika
      DJANGO_SUPERUSER_EMAIL: k1r1eiiika@example.com
      DJANGO_SUPERUSER_PASSWORD: 12345
    depends_on:
      - transactions_db
    ports:
      - "8002:8000"

  transactions_consumer:
    build:
      context: /backend/transactions_service
      dockerfile: Dockerfile
    command: [ "python", "transactions/services/transaction_consumer.py" ]
    environment:
      PYTHONPATH: /backend/transactions_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: transactions_service.settings
      RABBITMQ_HOST: rabbitmq  # Убедитесь, что consumer использует корректный хост
      RABBITMQ_PORT: 5672
    depends_on:
      - transactions_db
      - rabbitmq
    volumes:
      - .:/app

  transactions_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres_transactions
    ports:
      - "5433:5432"

  shopservice:
    build:
      context: /backend/shop_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: shop_service.settings
      DJANGO_SUPERUSER_USERNAME: k1r1eiiika
      DJANGO_SUPERUSER_EMAIL: k1r1eiiika@example.com
      DJANGO_SUPERUSER_PASSWORD: 12345
    depends_on:
      - shop_db
    ports:
      - "8003:8000"

  shop_consumer:
    build:
      context: /backend/shop_service
      dockerfile: Dockerfile
    command: [ "python", "shop/services/spend_money_consumer.py" ]
    environment:
      PYTHONPATH: /backend/shop_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: shop_service.settings
      RABBITMQ_HOST: rabbitmq  # Убедитесь, что consumer использует корректный хост
      RABBITMQ_PORT: 5672
    depends_on:
      - shop_db
      - rabbitmq
    volumes:
      - .:/app

  shop_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres_shop
    ports:
      - "5435:5432"

  notificationsservice:
    environment:
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: notifications_service.settings
      DJANGO_SUPERUSER_USERNAME: k1r1eiiika
      DJANGO_SUPERUSER_EMAIL: k1r1eiiika@example.com
      DJANGO_SUPERUSER_PASSWORD: 12345
    volumes:
      - .:/app
    build:
      context: /backend/notifications_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"