# Generated by Django 5.1.4 on 2024-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
