# Generated by Django 5.1.4 on 2024-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_itembundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembundle',
            name='price',
        ),
        migrations.AddField(
            model_name='itembundle',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
